### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')

### ISSUE THREAD

**Issue by thejimbirch** [mdlutz24/drupal-meeting-parser#23]
I can copy the first thread of a meeting. Trying to capture the next, or any longer thread never stops processing. I am shown the following error on the Extentions page of Chrome:

**Context**
https://app.slack.com/client/T06GX3JTS/C2THUBAVA

**Stack Trace**
js/scrape.js:80 (anonymous function)

`textNode = textNode.cloneNode(true);`

<img width="796" alt="Screenshot 2024-07-31 at 7 29 31 AM" src="https://github.com/user-attachments/assets/a0fd7e3b-4aa8-47f6-ad0c-f8324a7b5569">

**Comment by smustgrave** [comment]
Hitting this issue too

**Comment by hestenet** [comment]
+1 to this issue report. 

`Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at Object.parseText (scrape.js:80:25)
    at Object.<anonymous> (scrape.js:140:36)
    at NodeList.forEach (<anonymous>)
    at Object.parseThread (scrape.js:136:55)`
 
<img width="332" alt="Screenshot 2024-08-07 at 10 20 17 AM" src="https://github.com/user-attachments/assets/88932de3-2681-47b8-ae77-3010205dca8a">

**Comment by pameeela** [comment]
I'm getting this intermittently too. Some threads are fine but some just don't work at all. Can't quite see a pattern although anything with an embed seems to be a problem, e.g. linking to another slack message/thread or a link that pulls in metadata? Could be random though.

**Comment by goba** [comment]
Reproduced it. This was due to Slack changing their markup. Now consecutive messages will show up as individual messages WITHOUT the user information. So this trips up the number of children counter (child 4) as well as the user name extraction (once the children counter was out of the way). Fixed both in https://github.com/mdlutz24/drupal-meeting-parser/commit/e511d7788a4dab6885cce5a5c16addc354f32eb2 and works for me on the last autoupdates meeting that was otherwise broken.

<img width="360" alt="Screenshot 2024-08-07 at 22 26 12" src="https://github.com/user-attachments/assets/b71f40c5-6e48-4caa-9638-98dd4da013ca">

Please pull from git and reload the Extension in the Extension manager. Should work, fingers crossed.

**Comment by pameeela** [comment]
Ah, thank you!

**Comment by goba** [comment]
Made one more short followup fix for link parsing, worth pulling / reloading extension again if already done.

**Comment by pameeela** [comment]
Yes it's working now after a fresh pull :) Thanks again!

**Comment by mark-casias** [comment]
Thanks for the quick response. Confirmed success

**Comment by smustgrave** [comment]
Thanks for the quick fix!
