### ISSUE TITLE
Buttons no longer appearing since Slack UI update

### ISSUE THREAD

**Issue by RCheesley** [mdlutz24/drupal-meeting-parser#3]
Looks like there's a new Slack UI which has broken the meeting parser :(

![screenshot-app slack com-2020 03 27-16_47_56](https://user-images.githubusercontent.com/2930593/77779980-3870dc00-704b-11ea-8ce8-58c71f8f3e06.png)

**Comment by goba** [comment]
Whoops sorry for ignoring this issue. The Drupal Slack just switched over so I was hit by it myself. A z-index fix seems to have done it. I used the extension since then and it works fine otherwise. https://github.com/mdlutz24/drupal-meeting-parser/commit/8bd8bb5eeeaabc18c274749d8aeb07eb4d269662

You need to update your local checkout and reload the Chrome extension from the updated code for it to take effect.
