### ISSUE TITLE
<table> tag not created

### ISSUE THREAD

**Issue by quietone1** [mdlutz24/drupal-meeting-parser#4]
As of sometime in the last two weeks the` <table></table> `tags are not generated, the table rows are there. I have been adding them to the minutes by hand.

I am using Chromium
Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.9 (64-bit)

**Comment by goba** [comment]
Did you see a `scrape.js:75 Uncaught TypeError: Cannot read property 'childNodes' of null` at the same time? I think your meeting nodes may have missed some thread items too due to that. The commit I closed this with has a fix for my local issue which is essentially the same problem. Please open another issue if you still have problems with the updated code.
